version: '3'

services:
  bot:
    build: .
    tty: true
    volumes:
      - .:/go/src/bot
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:7.0.0-bullseye"
    volumes:
      - "redis-data:/data"

volumes:
  redis-data:
