version: '3'

services:
  bot:
    build: .
    volumes:
      - .:/go/src/bot
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: "postgres:16.4-alpine"
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: ${DB_TIMEZONE}
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data:
